global:
  message: Welcome to global order service dev environment!!
server:
  port: 8084
message: Hello from Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    username: root
    password: Shravan@1234567
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    
